Fix typo
`inerit` was meant to be to `inherit` probably, therefore `$ npm install chromium` fails on darwin:

```
default: throw new TypeError('Incorrect value of stdio option: ' + stdio);
               ^

TypeError: Incorrect value of stdio option: inerit
```